services:
  postgres:
    image: postgres:16
    container_name: app_database
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "54321:5432"
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
    networks:
      - local
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: postgresql://test:test@postgres:5432/test
    networks:
      - local
volumes:
  postgres_data:
networks:
  local:
    driver: bridge
